[2025-03-16T05:58:37.325+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T05:58:37.334+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_to_gsheets.upload_data_to_gsheets manual__2025-03-16T05:58:34.142783+00:00 [queued]>
[2025-03-16T05:58:37.339+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_to_gsheets.upload_data_to_gsheets manual__2025-03-16T05:58:34.142783+00:00 [queued]>
[2025-03-16T05:58:37.340+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-16T05:58:37.345+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_data_to_gsheets> on 2025-03-16 05:58:34.142783+00:00
[2025-03-16T05:58:37.349+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-16T05:58:37.350+0000] {standard_task_runner.py:72} INFO - Started process 120 to run task
[2025-03-16T05:58:37.351+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'upload_to_gsheets', 'upload_data_to_gsheets', 'manual__2025-03-16T05:58:34.142783+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/gsheet_dag.py', '--cfg-path', '/tmp/tmp1f110zfd']
[2025-03-16T05:58:37.352+0000] {standard_task_runner.py:105} INFO - Job 265: Subtask upload_data_to_gsheets
[2025-03-16T05:58:37.375+0000] {task_command.py:467} INFO - Running <TaskInstance: upload_to_gsheets.upload_data_to_gsheets manual__2025-03-16T05:58:34.142783+00:00 [running]> on host a6c6114aaeae
[2025-03-16T05:58:37.411+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_to_gsheets' AIRFLOW_CTX_TASK_ID='upload_data_to_gsheets' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T05:58:34.142783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T05:58:34.142783+00:00'
[2025-03-16T05:58:37.412+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-16T05:58:37.412+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-16T05:58:37.412+0000] {logging_mixin.py:190} INFO - Current task name:upload_data_to_gsheets state:running start_date:2025-03-16 05:58:37.334638+00:00
[2025-03-16T05:58:37.412+0000] {logging_mixin.py:190} INFO - Dag name:upload_to_gsheets and current dag run status:running
[2025-03-16T05:58:37.412+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-16T05:58:39.895+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gsheet_dag.py", line 79, in upload_to_gsheets
    sheet.append_rows(df.values.tolist())
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/worksheet.py", line 1858, in append_rows
    res = self.client.values_append(self.spreadsheet_id, range_label, params, body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/http_client.py", line 191, in values_append
    r = self.request("post", url, params=params, json=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/http_client.py", line 114, in request
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 537, in request
    response = super(AuthorizedSession, self).request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 370, in prepare
    self.prepare_body(data, files, json)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 510, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-03-16T05:58:39.915+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-16T05:58:39.916+0000] {logging_mixin.py:190} INFO - Task start:2025-03-16 05:58:37.334638+00:00 end:2025-03-16 05:58:39.914979+00:00 duration:2.580341
[2025-03-16T05:58:39.916+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): upload_data_to_gsheets> dag:<DAG: upload_to_gsheets> dagrun:<DagRun upload_to_gsheets @ 2025-03-16 05:58:34.142783+00:00: manual__2025-03-16T05:58:34.142783+00:00, state:running, queued_at: 2025-03-16 05:58:34.163611+00:00. externally triggered: True>
[2025-03-16T05:58:39.916+0000] {logging_mixin.py:190} INFO - Failure caused by Object of type date is not JSON serializable
[2025-03-16T05:58:39.917+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_to_gsheets, task_id=upload_data_to_gsheets, run_id=manual__2025-03-16T05:58:34.142783+00:00, execution_date=20250316T055834, start_date=20250316T055837, end_date=20250316T055839
[2025-03-16T05:58:39.938+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-16T05:58:39.938+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 265 for task upload_data_to_gsheets (Object of type date is not JSON serializable; 120)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gsheet_dag.py", line 79, in upload_to_gsheets
    sheet.append_rows(df.values.tolist())
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/worksheet.py", line 1858, in append_rows
    res = self.client.values_append(self.spreadsheet_id, range_label, params, body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/http_client.py", line 191, in values_append
    r = self.request("post", url, params=params, json=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gspread/http_client.py", line 114, in request
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 537, in request
    response = super(AuthorizedSession, self).request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 370, in prepare
    self.prepare_body(data, files, json)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 510, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-03-16T05:58:39.981+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T05:58:39.991+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T05:58:39.992+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
